chore(deps): add missing papaparse types
papaparse doesn't ship its own TypeScript definitions. We need to
install a separate package to grab them.

Remove ParseResult because parse() already declares its return
type and it's invalid:

    error TS2314: Generic type 'ParseResult<T>' requires 1 type argument(s).

Signed-off-by: Simon Ser <contact@emersion.fr>